## Numpy
Numpy is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.6 MB 5.5 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.6 MB 5.9 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.6 MB 6.6 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.6 MB 6.8 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.6 MB 7.4 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 8.2 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np

# Create arrays using numpy
## Create a 1d array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1)) # (Numpy array
print(arr1.shape) # (5,) # 1D array with 5 elements

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [11]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2 = arr2.reshape(1, 5) # Reshape to 2D array with 1 row and 5 columns 
print(arr2) # [[1 2 3 4 5]]

[[1 2 3 4 5]]


In [12]:
arr2 = np.array([[1, 2, 3, 4, 5]])
arr2.shape # (1, 5) # 2D array with 1 row and 5 columns

(1, 5)

In [13]:
#B 2D array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print(arr3.shape) # (2, 3) # 2D array with 2 rows and 3 columns

[[1 2 3]
 [4 5 6]]
(2, 3)


In [14]:
np.arange(0, 10, 2).reshape(5, 1) # Create an array with values from 0 to 10 with a step of 2 and reshape it to a 5x1 array


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3, 4)) # Create a 3x4 array filled with only 1s

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# Identity matrix
np.eye(3) # Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Attributes of numpy array

arr= np.array([[1, 2, 3], [4, 5, 6]])

print("Array\n", arr)
print("Shape of the array:", arr.shape) # (2, 3) # 2D array with 2 rows and 3 columns
print("Number of dimensions:", arr.ndim) # 2
print("Size of the array:", arr.size) # 6
print("Data type of the array:", arr.dtype) # int64(may vary based on the system)
print("Item size in bytes:", arr.itemsize) # 8 (may vary based on the system)

Array
 [[1 2 3]
 [4 5 6]]
Shape of the array: (2, 3)
Number of dimensions: 2
Size of the array: 6
Data type of the array: int64
Item size in bytes: 8


In [18]:
# Numpy Victorized Operations
arr1= np.array([1, 2, 3, 4, 5])
arr2= np.array([10, 20, 30, 40, 50])

# Element-wise addition
print("Addition:", arr1 + arr2) # [11 22 33 44 55]

# Element-wise subtraction
print("Subtraction:", arr1 - arr2) # [-9 -18 -27 -36 -45]

# Element-wise multiplication
print("Multiplication:", arr1 * arr2) # [ 10  40  90 160 250]

# Element-wise division
print("Division:", arr1 / arr2) # [0.1 0.1 0.1 0.1 0.1]



Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [20]:
# Universal Functions (ufuncs)

arr= np.array([1, 2, 3, 4, 5])
# Square root
print("Square root:", np.sqrt(arr)) # [1.         1.41421356 1.73205081 2.         2.23606798]
# Exponential
print("Exponential:", np.exp(arr)) # [ 2.71828183  7.3890561  20.08553692  54.59815003 148.4131591 ]
# Natural logarithm
print("Natural logarithm:", np.log(arr)) # [0.         0.69314718 1.09861229 1.38629436 1.60943791]
# Sine
print("Sine:", np.sin(arr)) # [0.84147098 0.90929743 0.14112001 -0.7568025 -0.95892427]
# Cosine
print("Cosine:", np.cos(arr)) # [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]

Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [28]:
# Array Indexing and Slicing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original Array:\n", arr)
# Indexing
print(arr[0, 1]) # 2
print(arr[0][1]) # 2
# Slicing
print("First row:", arr[0, :]) # [1 2 3 4]
print("First column:", arr[:, 0]) # [1 5 9]
print("Sub-array:\n", arr[0:2, 1:3]) # [[2 3] [6 7]]
print("Every second element in the first row:", arr[0, ::2]) # [1 3]
print("Every second row:", arr[::2, :]) # [[ 1  2  3  4] [ 9 10 11 12]]
print("Every second column:", arr[:, ::2]) # [[ 1  3] [ 5  7] [ 9 11]]
print("Reverse the array:\n", arr[::-1, ::-1]) # [[12 11 10  9] [ 8  7  6  5] [ 4  3  2  1]]
print("Reverse the first row:", arr[0, ::-1]) # [4 3 2 1]


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
2
First row: [1 2 3 4]
First column: [1 5 9]
Sub-array:
 [[2 3]
 [6 7]]
Every second element in the first row: [1 3]
Every second row: [[ 1  2  3  4]
 [ 9 10 11 12]]
Every second column: [[ 1  3]
 [ 5  7]
 [ 9 11]]
Reverse the array:
 [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Reverse the first row: [4 3 2 1]


In [29]:
# Modify Array elements

arr[0, 0] = 100
print("Modified Array:\n", arr) # [[100   2   3   4] [  5   6   7   8] [  9  10  11  12]]

Modified Array:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [33]:
arr[1:]=100
print("Modified Array:\n", arr) # This will change all elements in the second and third rows to 100
arr[:, 1]=200
print("Modified Array:\n", arr) # This will change all elements in the second column to 200
arr[:, :1]=300
print("Modified Array:\n", arr) # This will change all elements in the first column to 300

Modified Array:
 [[300 300 300 300]
 [100 100 100 100]
 [100 100 100 100]]
Modified Array:
 [[300 200 300 300]
 [100 200 100 100]
 [100 200 100 100]]
Modified Array:
 [[300 200 300 300]
 [300 200 100 100]
 [300 200 100 100]]


In [34]:
# Statistical Concepts- Normalization, Standardization, Mean, Median, Mode, Variance, Standard Deviation

## Normalization: to have a mean of 0 and a standard deviation of 1. This is done by subtracting the mean and dividing by the standard deviation.

### Calculate the mean and standard deviation of the array
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data) # [-1.26491106 -0.63245553  0.          0.63245553  1.26491106]

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [35]:
data= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean) # 5.5

# Median
median = np.median(data)
print("Median:", median) # 5.5

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev) # 2.8722813232690143

# variance
variance = np.var(data)
print("Variance:", variance) # 8.25

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [38]:
# Logical Operations

data= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[data > 5] # [ 6  7  8  9 10]
data[(data > 3) & (data < 8)] # [4 5 6 7]


array([4, 5, 6, 7])